#!/usr/bin/env bash

command -v jq >/dev/null 2>&1 || {
  echo >&2 "Program 'jq' required but it is not installed.
Aborting."
  exit 1
}
command -v curl >/dev/null 2>&1 || {
  echo >&2 "Program 'curl' required but is not installed.
Aborting."
  exit 1
}

APIKEY="32fd7ed47937b14d10e29d05d30f166c"
CITY_ID="610116"
URL="https://restapi.amap.com/v3/weather/weatherInfo?key=${APIKEY}&city=${CITY_ID}&extensions=base"

json=$(timeout --signal=1 2s curl -s "${URL}") || exit 1

# {
#     "status": "1",
#     "count": "1",
#     "info": "OK",
#     "infocode": "10000",
#     "lives": [
#         {
#             "province": "陕西",
#             "city": "长安区",
#             "adcode": "610116",
#             "weather": "雾",
#             "temperature": "3",
#             "winddirection": "北",
#             "windpower": "≤3",
#             "humidity": "97",
#             "reporttime": "2024-11-21 23:01:06",
#             "temperature_float": "3.0",
#             "humidity_float": "97.0"
#         }
#     ]
# }

PROVINCE=$(echo "$json" | jq -r '.lives[0].province')        # 城市
CITY=$(echo "$json" | jq -r '.lives[0].city')                # 城市
WEATHER_ICON=$(echo "$json" | jq -r '.lives[0].weather')     # 天气状况（如雾）
WEATHER_TEMP=$(echo "$json" | jq -r '.lives[0].temperature') # 温度
WIND_SPEED=$(echo "$json" | jq -r '.lives[0].windpower')     # 风速
WIND_DIR=$(echo "$json" | jq -r '.lives[0].winddirection')   # 风向

echo " ${PROVINCE}${CITY} ${WEATHER_ICON} ${WEATHER_TEMP}°C: ${WIND_SPEED} km/h ${WIND_DIR}"
